"""Add Artist model and update Music model

Revision ID: 67645e91477a
Revises: 3b598df017d8
Create Date: 2024-10-04 11:12:01.309550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67645e91477a'
down_revision = '3b598df017d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'])
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    op.drop_table('artists')
    # ### end Alembic commands ###
